title: <p align="center"> Akshay Thakur </p>
logo: /assets/img/logo.png

description:
  <p align="center">
  <a href="assets/img/Akshay_Thakur_product (2).pdf">Resume</a> |
  <a href="www.linkedin.com/in/akshay-thakur-59249193">LinkedIn</a> |
  <a href="https://github.com/Akshay01Thakur">GitHub</a>
  
  <br>   
  A proven understanding of information technology, knowledgeable in disruptive technologies, in-depth
  experience and knowledge of databases and data schema. Good knowledge in SQL and NOSQL
  databases MySQL, PGadmin, Snowflake, MongoDB and Oracle. 
  <br>
  </p>




