title: "<p align='center'>Akshay Thakur</p>"
logo: "/assets/img/logo.png"

description: |
  <p align="center">
  <a href="assets/img/Akshay_Thakur_product (2).pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/akshay-thakur-59249193/">LinkedIn</a> |
  <a href="https://github.com/Akshay01Thakur">GitHub</a>

  <br><br><br><br><br><br>   
  A proven understanding of information technology, knowledgeable in disruptive technologies
  <br>
  </p>
